version: '3'

services:
  api-service:
    build: ./backend
    volumes:
      - ./backend:/usr/src/backend
    ports:
     - "5000:5000"

  client-service:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/frontend
    ports:
     - "8080:8080"
    depends_on:
      - api-service

