version: '3'

services:
  api-gateway:
    build: api-gateway
    volumes:
      - ./api-gateway:/usr/src/api-gateway
    ports:
     - "5000:5000"

  api-inventory:
    build: api-inventory
    volumes:
      - ./api-inventory:/usr/src/api-inventory
    ports:
      - "5001:5001"
    depends_on:
      - api-gateway

  client:
    build: client
    volumes:
      - ./client:/usr/src/client
    ports:
     - "8080:8080"
    depends_on:
      - api-gateway

