version: '3'

services:
  api-service:
    build: api-gateway
    volumes:
      - ./api-gateway:/usr/src/api-gateway
    ports:
     - "5000:5000"

  client-service:
    build: client
    volumes:
      - ./client:/usr/src/client
    ports:
     - "8080:8080"
    depends_on:
      - api-service

